### ISSUE TITLE
Uncaught (in promise) when want to sign in with google

### ISSUE THREAD

**Issue by leoboom-isme** [devbaji/vue3-google-login#60]
Can't seem to get this library to work.

My code:

    <script setup>
        import { ref } from "vue";
        import Button from "@/components/ui/Button.vue";
        import { googleAuthCodeLogin } from "vue3-google-login"

        const googleClientId = ref(<client id text>);

        const googleLogin = () => {
            googleAuthCodeLogin({clientId: googleClientId}).then((response) => {
                console.log("Handle the response", response)
            })
        }
    </script>

    <template>
        <div>
            <p class="tw-text-light tw-text-center">Or sign in with</p>
            <div class="tw-mt-5 tw-grid tw-grid-cols-2 tw-gap-4">
                <Button @click="googleLogin" >
                    <span>Google</span>
                </Button>
            </div>
        </div>
    </template>

![image](https://github.com/user-attachments/assets/3cd35b55-59d6-4a10-ad4a-07bdd13bcbb2)

Vue: 3.4
vue3-google-login: 2.0.26

**Comment by devbaji** [comment]
@leoboom-isme In this line
`googleAuthCodeLogin({clientId: googleClientId}).then((response) => {`
Change googleClientId to googleClientId.value.

Inside <script> you need to use `.value` to access ref value, [see here](https://vuejs.org/api/reactivity-core.html#ref)

One more this most case clientId doesn't change for an app, if the clientId doesn't change, just make it as a normal const variable instead of making it ref. 
Also I suggest you to initialise clientId this in main.js [see here](https://devbaji.github.io/vue3-google-login/#initialize-the-plugin)
